### ISSUE TITLE
`fields_hidden_by_default: yes` is removed

### ISSUE THREAD

**Issue by Jacky56** [looker-open-source/pylookml#70]
Hello all,

Upon performing `lookml.File("file_path").write()` it will remove some key values such as `fields_hidden_by_default: yes` on version `3.0.3`

To recreate:

the file:
```yaml
view: view_name {
  fields_hidden_by_default: yes

  dimension: pk {
    description: "some pk"
    type: string
    primary_key: yes
    sql: ${TABLE}."pk" ;;
  }

  dimension: name_of_cats {
    description: "names of cats"
    type: string
    sql: ${TABLE}."name_of_cats" ;;
  }
}
```

the code:
```python3
import lookml

file_path = "path/to/yaml.view.lookml"
view_file = lookml.File(file_path)
view_file.write()
```
